version: '3.8'

services:
  postgres_db:
    image: postgres:16
    environment:
      POSTGRES_USER: bernate_juan
      POSTGRES_PASSWORD: Jbernate
      POSTGRES_DB: bernate_juan_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
